query($id: Int!) {
  matches_by_pk(id: $id) {
    id
    name
    budget
    environments {
      id
      public
      key
      value
    }
    created_at
    updated_at
    competition {
      id
      public
      owner { name }
    }
    problem {
      id
      public
      image
      description_en
      description_ja
      owner { name }
      created_at
      updated_at
    }
    indicator {
      id
      public
      image
      description_en
      description_ja
      owner { name }
      created_at
      updated_at
    }
  }
}
