query($id: String!) {
  problems_by_pk(id: $id) {
    id
    public
    image
    description_en
    description_ja
    created_at
    updated_at
    owner { name }
    matches {
      id
      name
      competition {
        id
        public
        owner { name }
      }
      budget
      created_at
      updated_at
    }
  }
}
