query(
  $offset: Int = 0
  $limit: Int = 100
  $where: indicators_bool_exp = {}
) {
  indicators(offset: $offset, limit: $limit, where: $where) {
    id
    public
    owner { name }
    matches {
      id
      competition_id
      name
    }
    created_at
    updated_at
  }
}
